pipeline {
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/DanielDKing/NetoMedia_Interview.git'
      }
    }
    stage('Template the kubernetes creation yml ') {
      steps{
        ansiblePlaybook(
          playbook: './deploy/template.yml',
          extraVars: [
			  buildId: '$BUILD_NUMBER',
              tagName: '$TAG_NAME',
              jobName: '$JOB_NAME'
          ])
      }
    }
    stage('Deploy the application on kubernetes cluster') {
        steps{
            sh "/usr/local/bin/kubectl --insecure-skip-tls-verify=true apply -f /var/lib/jenkins/workspace/$JOB_NAME/deploy/flask-deployment.yml"
        }
    }
  }
}